param_list:
  # [첫 번째 라이다: OT128]
  - source_type: 1                  # 1: Real-time UDP
    lidar_udp_type:
      device_ip_address: "192.168.20.201" # OT128 IP
      udp_port: 2368                # OT128 Port
      ptc_port: 10110
      correction_file_path: ""
      firetime_file_path: ""
      multicast_ip: ""
    ros:
      ros_frame_id: "ot128_frame"
      ros_recv_packet_topic: "/ot128/lidar_packets"
      ros_send_point_cloud_topic: "/ot128/hesai/pandar" # 토픽 이름 1
      send_packet_ros: false
      send_point_cloud_ros: true

  # [두 번째 라이다: QT128] (하이픈 - 위치 주의)
  - source_type: 1
    lidar_udp_type:
      device_ip_address: "192.168.20.202" # QT128 IP
      udp_port: 2369                # QT128 Port (2368과 달라야 함)
      ptc_port: 10110
      correction_file_path: ""
      firetime_file_path: ""
      multicast_ip: ""
    ros:
      ros_frame_id: "qt128_frame"
      ros_recv_packet_topic: "/qt128/lidar_packets"
      ros_send_point_cloud_topic: "/qt128/hesai/pandar_qt" # 토픽 이름 2
      send_packet_ros: false
      send_point_cloud_ros: true
